In [1]:
import pandas as pd
import numpy as np

import wrangle

In [2]:
ercot = wrangle.get_ercot_df()

In [3]:
ercot.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 109535 entries, 2010-01-01 00:00:00 to 2022-06-30 23:00:00
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ercot_load      109535 non-null  float64
 1   dow             109535 non-null  object
 2   is_weekday      109535 non-null  int64
 3   is_obs_holiday  109535 non-null  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 4.2+ MB

In [4]:
weather = pd.read_csv('clean_weather_df.csv',index_col='datetime',parse_dates=['datetime'])

In [9]:
weather.index.minute.value_counts()

0    109536
Name: datetime, dtype: int64

In [24]:
weather.loc['2017-11-05']

,hs_temp,hs_feelslike,hs_dew,hs_humidity,hs_precip,hs_windgust,hs_windspeed,hs_winddir,hs_sealevelpressure,hs_cloudcover,...,vc_precip,vc_windgust,vc_windspeed,vc_winddir,vc_sealevelpressure,vc_cloudcover,vc_visibility,vc_solarradiation,vc_solarenergy,vc_uvindex
datetime,,,,,,,,,,,,,,,,,,,,,
2017-11-05 00:00:00,74.2,74.2,73.30,97.13,0.0,15.0,7.40,171.0,1015.8,8.5,...,0.0,10.30,7.00,160.0,1015.1,54.80,6.3,0.0,NaN,0.0
2017-11-05 01:00:00,73.6,73.6,73.35,99.17,0.0,12.8,7.75,170.5,1015.5,57.4,...,0.0,11.55,6.55,174.5,1014.9,92.15,4.4,0.0,NaN,0.0
2017-11-05 02:00:00,73.6,73.6,73.40,99.24,0.0,NaN,4.50,49.0,1015.3,70.3,...,0.0,11.40,7.00,170.0,1014.4,95.40,5.0,0.0,NaN,0.0
2017-11-05 03:00:00,73.6,73.6,73.40,99.26,0.0,NaN,4.20,180.0,1014.9,91.6,...,0.0,NaN,7.00,180.0,1013.9,96.00,3.9,0.0,NaN,0.0
2017-11-05 04:00:00,73.6,73.6,73.40,99.12,0.0,17.2,0.90,18.0,1014.7,94.6,...,0.0,15.00,5.00,180.0,1013.9,95.00,3.2,0.0,NaN,0.0
2017-11-05 05:00:00,73.6,73.6,73.40,99.26,0.0,NaN,0.80,306.0,1014.8,93.0,...,0.0,12.80,6.00,180.0,1013.9,71.40,3.8,0.0,NaN,0.0
2017-11-05 06:00:00,73.6,73.6,73.40,99.26,0.0,11.4,3.30,54.0,1015.2,74.9,...,0.0,12.80,4.90,180.0,1014.1,59.60,2.6,0.0,NaN,0.0
2017-11-05 07:00:00,73.6,73.6,73.40,99.26,0.0,NaN,0.70,53.0,1015.7,93.5,...,0.0,11.40,7.00,171.0,1014.5,96.50,2.6,60.3,0.2,1.0
2017-11-05 08:00:00,75.3,75.3,73.50,94.28,0.0,NaN,4.40,162.0,1016.0,70.1,...,0.0,NaN,3.50,170.0,1015.1,57.50,4.0,253.5,0.9,3.0
2017-11-05 09:00:00,78.2,78.2,73.60,85.74,0.0,NaN,4.30,306.0,1016.7,72.2,...,0.0,NaN,9.60,190.0,1015.8,63.20,7.1,449.0,1.6,4.0
2017-11-05 10:00:00,80.2,84.0,71.90,76.08,0.0,15.3,8.30,206.0,1016.7,74.0,...,0.0,20.80,15.00,199.0,1016.2,30.00,9.9,605.5,2.2,6.0
2017-11-05 11:00:00,84.7,88.7,69.30,60.05,0.0,17.2,9.20,217.0,1016.6,43.6,...,0.0,22.90,17.90,190.0,1015.5,89.40,9.9,705.5,2.5,7.0
2017-11-05 12:00:00,86.1,88.9,66.90,52.86,0.0,19.7,9.80,193.0,1015.5,64.6,...,0.0,18.30,14.80,181.0,1014.8,49.00,9.9,735.3,2.6,7.0
2017-11-05 13:00:00,87.3,90.1,66.60,50.41,0.0,22.8,10.10,208.0,1014.3,88.3,...,0.0,21.90,15.90,208.0,1013.8,3.20,9.9,700.8,2.5,7.0
2017-11-05 14:00:00,88.4,91.3,66.60,48.54,0.0,21.0,12.10,212.0,1013.7,26.0,...,0.0,20.80,13.80,190.0,1012.9,3.20,9.9,599.5,2.2,6.0
2017-11-05 15:00:00,87.7,90.5,66.60,49.67,0.0,16.6,7.90,193.0,1013.5,17.0,...,0.0,21.90,13.90,190.0,1012.6,0.00,9.9,443.1,1.6,4.0
2017-11-05 16:00:00,86.8,90.0,67.50,52.82,0.0,16.8,9.00,168.0,1013.3,32.7,...,0.0,19.90,15.70,161.0,1012.3,0.00,9.9,246.4,0.9,2.0
2017-11-05 17:00:00,83.4,86.6,68.20,60.40,0.0,15.6,7.00,174.0,1013.1,6.4,...,0.0,20.80,15.00,160.0,1012.3,0.00,9.9,56.7,0.2,1.0
2017-11-05 18:00:00,80.7,83.9,69.40,68.42,0.0,NaN,5.90,180.0,1013.8,6.4,...,0.0,12.80,12.70,160.0,1012.6,0.00,9.9,0.0,NaN,0.0
2017-11-05 19:00:00,78.9,78.9,70.20,74.72,0.0,NaN,9.60,165.0,1014.3,12.9,...,0.0,15.00,11.40,160.0,1013.4,0.00,9.9,0.0,NaN,0.0
2017-11-05 20:00:00,77.2,77.2,72.00,84.13,0.0,NaN,8.40,159.0,1015.2,9.1,...,0.0,NaN,8.10,150.0,1014.0,0.00,9.9,0.0,NaN,0.0
2017-11-05 21:00:00,75.5,75.5,73.60,93.76,0.0,NaN,12.00,160.0,1015.5,39.5,...,0.0,NaN,9.20,150.0,1014.5,0.00,8.7,0.0,NaN,0.0
2017-11-05 22:00:00,75.3,75.3,73.60,94.28,0.0,17.2,9.70,152.0,1015.5,90.6,...,0.0,17.20,10.40,170.0,1014.5,84.50,8.7,0.0,NaN,0.0
2017-11-05 23:00:00,75.5,75.5,73.60,93.90,0.0,NaN,10.50,162.0,1015.4,96.6,...,0.0,NaN,11.20,170.0,1014.9,94.80,9.9,0.0,NaN,0.0

In [25]:
weather.loc['2017-03-12']

,hs_temp,hs_feelslike,hs_dew,hs_humidity,hs_precip,hs_windgust,hs_windspeed,hs_winddir,hs_sealevelpressure,hs_cloudcover,...,vc_precip,vc_windgust,vc_windspeed,vc_winddir,vc_sealevelpressure,vc_cloudcover,vc_visibility,vc_solarradiation,vc_solarenergy,vc_uvindex
datetime,,,,,,,,,,,,,,,,,,,,,
2017-03-12 00:00:00,62.8,62.8,62.6,99.25,0.06,NaN,9.9,39.0,1019.2,86.1,...,0.01,NaN,11.6,21.0,1017.7,75.1,8.6,0.0,NaN,0.0
2017-03-12 01:00:00,62.6,62.6,62.3,99.16,0.01,19.2,15.3,42.0,1019.6,90.7,...,0.00,27.7,14.2,21.0,1017.9,63.1,9.4,0.0,NaN,0.0
2017-03-12 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-12 03:00:00,59.0,59.0,57.1,93.56,0.00,20.8,10.7,32.0,1019.6,99.4,...,0.00,NaN,12.3,16.0,1018.1,92.9,9.5,0.0,NaN,0.0
2017-03-12 04:00:00,56.1,56.1,54.1,93.23,0.00,20.4,15.2,40.0,1019.8,100.0,...,0.00,NaN,12.5,20.0,1017.7,91.7,8.8,0.0,NaN,0.0
2017-03-12 05:00:00,53.6,53.6,50.8,90.16,0.00,24.2,19.2,16.0,1020.2,100.0,...,0.00,20.5,11.7,29.0,1017.9,97.2,9.9,0.0,NaN,0.0
2017-03-12 06:00:00,51.2,51.2,48.3,89.83,0.00,26.3,16.8,9.0,1021.0,100.0,...,0.00,21.9,15.1,21.0,1018.5,96.8,8.8,0.0,NaN,0.0
2017-03-12 07:00:00,50.2,50.2,46.7,87.51,0.00,25.3,16.7,2.0,1021.6,100.0,...,0.01,31.4,22.4,10.0,1019.9,98.7,3.4,3.1,0.0,0.0
2017-03-12 08:00:00,49.1,42.9,45.6,87.41,0.00,24.1,17.6,6.0,1022.4,100.0,...,0.00,31.9,20.9,19.0,1020.9,98.8,6.2,66.2,0.2,1.0
2017-03-12 09:00:00,48.3,42.1,44.8,87.84,0.00,27.9,16.2,23.0,1023.2,100.0,...,0.00,26.4,16.2,19.0,1021.9,98.8,3.8,207.7,0.7,2.0
2017-03-12 10:00:00,48.3,42.6,44.7,87.55,0.00,20.5,14.4,16.0,1023.7,100.0,...,0.00,29.5,15.3,10.0,1022.7,98.4,8.4,378.4,1.4,4.0
2017-03-12 11:00:00,48.3,42.5,44.7,87.41,0.00,16.1,15.0,2.0,1024.1,100.0,...,0.00,24.2,16.2,11.0,1023.0,98.8,6.2,509.4,1.8,5.0
2017-03-12 12:00:00,48.4,42.5,44.7,87.03,0.00,18.3,15.5,5.0,1023.9,100.0,...,0.00,23.7,18.3,29.0,1023.0,98.8,9.9,608.0,2.2,6.0
2017-03-12 13:00:00,49.5,45.0,43.1,78.55,0.00,NaN,11.1,5.0,1023.5,100.0,...,0.00,24.2,16.2,10.0,1022.5,98.8,9.9,688.8,2.5,7.0
2017-03-12 14:00:00,52.8,52.8,44.8,74.14,0.00,NaN,8.4,32.0,1022.7,100.0,...,0.00,NaN,15.0,10.0,1022.1,98.8,9.9,633.8,2.3,6.0
2017-03-12 15:00:00,56.5,56.5,45.0,65.24,0.00,NaN,9.8,26.0,1021.7,98.9,...,0.00,NaN,12.8,10.0,1021.5,98.8,9.9,470.5,1.7,5.0
2017-03-12 16:00:00,59.0,59.0,46.6,63.60,0.00,NaN,7.0,6.0,1020.9,92.7,...,0.00,NaN,10.6,19.0,1021.2,98.8,9.9,292.1,1.1,3.0
2017-03-12 17:00:00,59.2,59.2,46.6,63.00,0.00,NaN,8.0,10.0,1020.6,21.2,...,0.00,NaN,13.8,11.0,1020.5,98.8,9.9,156.3,0.6,2.0
2017-03-12 18:00:00,59.3,59.3,47.7,65.50,0.00,NaN,7.4,348.0,1019.8,8.5,...,0.00,18.3,13.6,11.0,1020.0,98.8,9.9,58.5,0.2,1.0
2017-03-12 19:00:00,58.2,58.2,48.3,69.63,0.00,NaN,0.6,356.0,1020.0,56.9,...,0.00,NaN,8.0,20.0,1021.0,98.8,9.9,3.6,0.0,0.0
2017-03-12 20:00:00,59.1,59.1,48.4,67.45,0.00,NaN,0.7,341.0,1020.0,98.4,...,0.00,NaN,8.6,48.0,1021.0,98.8,9.9,0.0,NaN,0.0
2017-03-12 21:00:00,57.5,57.5,48.4,71.41,0.00,NaN,1.0,343.0,1020.4,98.4,...,0.00,NaN,6.5,48.0,1020.8,98.8,9.9,0.0,NaN,0.0
2017-03-12 22:00:00,57.4,57.4,48.3,71.67,0.00,NaN,6.4,308.0,1020.1,98.4,...,0.00,NaN,5.4,29.0,1020.6,98.8,9.9,0.0,NaN,0.0
2017-03-12 23:00:00,55.6,55.6,48.3,76.20,0.00,NaN,5.4,319.0,1019.9,97.5,...,0.00,NaN,7.6,57.0,1020.4,98.8,9.9,0.0,NaN,0.0

In [33]:
weather[weather.hs_temp.isna()].index

DatetimeIndex(['2010-03-14 02:00:00', '2011-03-13 02:00:00',
               '2012-03-11 02:00:00', '2013-03-10 02:00:00',
               '2014-03-09 02:00:00', '2015-03-08 02:00:00',
               '2016-03-13 02:00:00', '2017-03-12 02:00:00',
               '2018-03-11 02:00:00', '2019-03-10 02:00:00',
               '2020-03-08 02:00:00', '2021-03-14 02:00:00',
               '2022-03-13 02:00:00'],
              dtype='datetime64[ns]', name='datetime', freq=None)

In [ ]:
# df.drop(index=weather[weather.hs_temp.isna()].index)

In [26]:
tz_w = weather.copy()

In [31]:
tz_w.loc['2010-11-07']

,hs_temp,hs_feelslike,hs_dew,hs_humidity,hs_precip,hs_windgust,hs_windspeed,hs_winddir,hs_sealevelpressure,hs_cloudcover,...,vc_precip,vc_windgust,vc_windspeed,vc_winddir,vc_sealevelpressure,vc_cloudcover,vc_visibility,vc_solarradiation,vc_solarenergy,vc_uvindex
datetime,,,,,,,,,,,,,,,,,,,,,
2010-11-07 00:00:00,54.10,54.10,39.3,57.270,0.0,NaN,6.8,147.0,1029.9,0.0,...,0.0,NaN,3.4,80.0,1028.9,0.0,9.9,0.0,NaN,0.0
2010-11-07 01:00:00,54.05,54.05,37.8,54.045,0.0,NaN,4.9,138.0,1029.8,0.0,...,0.0,NaN,4.7,65.0,1028.7,0.0,9.9,0.0,NaN,0.0
2010-11-07 02:00:00,53.80,53.80,38.0,55.110,0.0,NaN,5.8,129.0,1029.6,0.0,...,0.0,NaN,8.0,50.0,1028.4,0.0,9.9,0.0,NaN,0.0
2010-11-07 03:00:00,53.80,53.80,38.0,55.110,0.0,NaN,5.8,129.0,1029.3,0.0,...,0.0,NaN,6.9,60.0,1028.3,0.0,9.9,0.0,NaN,0.0
2010-11-07 04:00:00,53.80,53.80,38.0,55.110,0.0,NaN,5.8,110.0,1029.1,0.0,...,0.0,NaN,6.9,70.0,1028.1,0.0,9.9,0.0,NaN,0.0
2010-11-07 05:00:00,52.20,52.20,40.8,65.130,0.0,NaN,5.8,83.0,1029.3,0.0,...,0.0,NaN,5.8,70.0,1028.1,0.0,9.9,0.0,NaN,0.0
2010-11-07 06:00:00,53.70,53.70,43.9,69.220,0.0,NaN,4.9,46.0,1029.2,0.0,...,0.0,NaN,5.8,60.0,1027.9,0.0,9.9,0.0,NaN,0.0
2010-11-07 07:00:00,50.70,50.70,39.6,65.550,0.0,NaN,5.8,46.0,1029.7,0.0,...,0.0,NaN,5.8,60.0,1028.2,0.0,9.9,62.6,0.2,1.0
2010-11-07 08:00:00,54.80,54.80,41.9,61.580,0.0,NaN,4.0,73.0,1030.3,0.0,...,0.0,NaN,6.9,60.0,1028.5,0.0,9.9,264.5,1.0,3.0
2010-11-07 09:00:00,58.80,58.80,41.3,52.250,0.0,NaN,6.9,65.0,1030.6,0.0,...,0.0,NaN,8.1,70.0,1028.9,0.0,9.9,463.8,1.7,5.0
2010-11-07 10:00:00,62.40,62.40,39.6,42.910,0.0,NaN,7.7,90.0,1030.7,4.4,...,0.0,NaN,12.7,90.0,1029.1,0.0,9.9,621.5,2.2,6.0
2010-11-07 11:00:00,64.40,64.40,40.8,41.980,0.0,NaN,6.8,95.0,1030.3,0.0,...,0.0,NaN,10.3,130.0,1028.8,0.0,9.9,722.0,2.6,7.0
2010-11-07 12:00:00,66.20,66.20,41.4,40.260,0.0,NaN,4.7,100.0,1029.5,4.4,...,0.0,17.2,9.2,150.0,1027.9,26.9,9.9,755.3,2.7,8.0
2010-11-07 13:00:00,67.80,67.80,42.9,40.500,0.0,NaN,3.7,68.0,1028.1,0.0,...,0.0,17.2,13.8,130.0,1026.7,49.0,9.9,719.8,2.6,7.0
2010-11-07 14:00:00,68.10,68.10,42.9,40.070,0.0,NaN,1.1,70.0,1027.2,0.0,...,0.0,19.5,8.1,130.0,1025.8,0.0,9.9,617.5,2.2,6.0
2010-11-07 15:00:00,68.10,68.10,41.3,37.690,0.0,NaN,6.4,160.0,1026.6,0.0,...,0.0,NaN,8.1,120.0,1025.1,26.9,9.9,457.9,1.6,5.0
2010-11-07 16:00:00,67.80,67.80,43.2,40.840,0.0,NaN,6.8,120.0,1026.3,0.0,...,0.0,NaN,9.2,120.0,1024.8,0.0,9.9,259.3,0.9,3.0
2010-11-07 17:00:00,64.50,64.50,44.6,48.410,0.0,NaN,4.7,125.0,1026.0,0.0,...,0.0,NaN,10.3,120.0,1024.6,0.0,9.9,60.3,0.2,1.0
2010-11-07 18:00:00,62.40,62.40,42.9,48.810,0.0,NaN,7.7,110.0,1025.9,0.0,...,0.0,NaN,5.8,120.0,1024.6,0.0,9.9,0.0,NaN,0.0
2010-11-07 19:00:00,58.80,58.80,41.3,52.110,0.0,NaN,8.6,157.0,1025.6,0.0,...,0.0,NaN,5.8,120.0,1024.6,0.0,9.9,0.0,NaN,0.0
2010-11-07 20:00:00,57.00,57.00,42.9,59.260,0.0,NaN,8.5,148.0,1025.7,0.0,...,0.0,NaN,5.8,120.0,1024.6,0.0,9.9,0.0,NaN,0.0
2010-11-07 21:00:00,56.70,56.70,44.7,64.030,0.0,NaN,8.5,157.0,1025.6,0.0,...,0.0,NaN,5.8,110.0,1024.6,0.0,9.9,0.0,NaN,0.0
2010-11-07 22:00:00,56.10,56.10,46.2,69.260,0.0,NaN,7.3,150.0,1025.4,0.0,...,0.0,NaN,4.7,120.0,1024.6,0.0,9.9,0.0,NaN,0.0
2010-11-07 23:00:00,56.40,56.40,46.2,68.700,0.0,NaN,8.7,147.0,1025.2,0.0,...,0.0,NaN,4.7,100.0,1024.2,0.0,9.9,0.0,NaN,0.0

In [30]:
tz_w.tz_localize('US/Central',ambiguous='infer',nonexistent='NaT')

AmbiguousTimeError: 2010-11-07 01:00:00

In [10]:
er_list = list(ercot.index)
w_list = list(weather.index)

In [11]:
len(er_list)

109535

In [12]:
len(w_list)

109536

In [14]:
set(w_list) - set(er_list)

{Timestamp('2010-03-14 02:00:00'),
 Timestamp('2011-03-13 02:00:00'),
 Timestamp('2012-03-11 02:00:00'),
 Timestamp('2013-03-10 02:00:00'),
 Timestamp('2014-03-09 02:00:00'),
 Timestamp('2015-03-08 02:00:00'),
 Timestamp('2016-03-13 02:00:00'),
 Timestamp('2017-03-12 03:00:00'),
 Timestamp('2018-03-11 03:00:00'),
 Timestamp('2019-03-10 03:00:00'),
 Timestamp('2020-03-08 03:00:00'),
 Timestamp('2021-03-14 03:00:00'),
 Timestamp('2022-03-13 03:00:00')}

In [18]:
ercot.loc['2010-11-07']

                      ercot_load     dow  is_weekday  is_obs_holiday
datetime
2010-11-07 00:00:00  7487.208500  Sunday           0               0
2010-11-07 01:00:00  7218.432121  Sunday           0               0
2010-11-07 02:00:00  7051.515830  Sunday           0               0
2010-11-07 02:00:00  6914.202568  Sunday           0               0
2010-11-07 03:00:00  6881.075592  Sunday           0               0
2010-11-07 04:00:00  6886.134142  Sunday           0               0
2010-11-07 05:00:00  6975.323383  Sunday           0               0
2010-11-07 06:00:00  7161.669600  Sunday           0               0
2010-11-07 07:00:00  7366.010375  Sunday           0               0
2010-11-07 08:00:00  7523.301696  Sunday           0               0
2010-11-07 09:00:00  7786.921692  Sunday           0               0
2010-11-07 10:00:00  7963.236536  Sunday           0               0
2010-11-07 11:00:00  8026.067869  Sunday           0               0
2010-11-07 12:00:00  8006.488002  Sunday           0               0
2010-11-07 13:00:00  8022.637460  Sunday           0               0
2010-11-07 14:00:00  8000.359620  Sunday           0               0
2010-11-07 15:00:00  8026.695710  Sunday           0               0
2010-11-07 16:00:00  8058.450801  Sunday           0               0
2010-11-07 17:00:00  8062.872369  Sunday           0               0
2010-11-07 18:00:00  8370.172752  Sunday           0               0
2010-11-07 19:00:00  8739.362655  Sunday           0               0
2010-11-07 20:00:00  8566.353158  Sunday           0               0
2010-11-07 21:00:00  8482.993443  Sunday           0               0
2010-11-07 22:00:00  8154.254741  Sunday           0               0
2010-11-07 23:00:00  7765.257100  Sunday           0               0

In [20]:
import pytz

In [22]:
pytz.all_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'America/Anguilla', 'America/Antigua', 'America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/ComodRivadavia', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Aruba', 'America/Asuncion', 'America/Atikokan', 'America/Atka', 'America/Bahia', 'America/Bahia_Banderas', 'America/Barbados', 'America/Belem', 'America/Belize', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Bogota', 'America/Boise', 'America/Buenos_Aires', 'America/Cambridge_Bay', 'America/Campo_Grande', 'America/Cancun', 'America/Caracas', 'America/Catamarca', 'America/Cayenne', 'America/Cayman', 'America/Chicago', 'America/Chihuahua', 'America/Coral_Harbour', 'America/Cordoba', 'America/Costa_Rica', 'America/Creston', 'America/Cuiaba', 'America/Curacao', 'America/Danmarkshavn', 'America/Dawson', 'America/Dawson_Creek', 'America/Denver', 'America/Detroit', 'America/Dominica', 'America/Edmonton', 'America/Eirunepe', 'America/El_Salvador', 'America/Ensenada', 'America/Fort_Nelson', 'America/Fort_Wayne', 'America/Fortaleza', 'America/Glace_Bay', 'America/Godthab', 'America/Goose_Bay', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guatemala', 'America/Guayaquil', 'America/Guyana', 'America/Halifax', 'America/Havana', 'America/Hermosillo', 'America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Indianapolis', 'America/Inuvik', 'America/Iqaluit', 'America/Jamaica', 'America/Jujuy', 'America/Juneau', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Knox_IN', 'America/Kralendijk', 'America/La_Paz', 'America/Lima', 'America/Los_Angeles', 'America/Louisville', 'America/Lower_Princes', 'America/Maceio', 'America/Managua', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Matamoros', 'America/Mazatlan', 'America/Mendoza', 'America/Menominee', 'America/Merida', 'America/Metlakatla', 'America/Mexico_City', 'America/Miquelon', 'America/Moncton', 'America/Monterrey', 'America/Montevideo', 'America/Montreal', 'America/Montserrat', 'America/Nassau', 'America/New_York', 'America/Nipigon', 'America/Nome', 'America/Noronha', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Nuuk', 'America/Ojinaga', 'America/Panama', 'America/Pangnirtung', 'America/Paramaribo', 'America/Phoenix', 'America/Port-au-Prince', 'America/Port_of_Spain', 'America/Porto_Acre', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Punta_Arenas', 'America/Rainy_River', 'America/Rankin_Inlet', 'America/Recife', 'America/Regina', 'America/Resolute', 'America/Rio_Branco', 'America/Rosario', 'America/Santa_Isabel', 'America/Santarem', 'America/Santiago', 'America/Santo_Domingo', 'America/Sao_Paulo', 'America/Scoresbysund', 'America/Shiprock', 'America/Sitka', 'America/St_Barthelemy', 'America/St_Johns', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Thule', 'America/Thunder_Bay', 'America/Tijuana', 'America/Toronto', 'America/Tortola', 'America/Vancouver', 'America/Virgin', 'America/Whitehorse', 'America/Winnipeg', 'America/Yakutat', 'America/Yellowknife', 'Antarctica/Casey', 'Antarctica/Davis', 'Antarctica/DumontDUrville', 'Antarctica/Macquarie', 'Antarctica/Mawson', 'Antarctica/McMurdo', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Antarctica/South_Pole', 'Antarctica/Syowa', 'Antarctica/Troll', 'Antarctica/Vostok', 'Arctic/Longyearbyen', 'Asia/Aden', 'Asia/Almaty', 'Asia/Amman', 'Asia/Anadyr', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Ashkhabad', 'Asia/Atyrau', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Baku', 'Asia/Bangkok', 'Asia/Barnaul', 'Asia/Beirut', 'Asia/Bishkek', 'Asia/Brunei', 'Asia/Calcutta', 'Asia/Chita', 'Asia/Choibalsan', 'Asia/Chongqing', 'Asia/Chungking', 'Asia/Colombo', 'Asia/Dacca', 'Asia/Damascus', 'Asia/Dhaka', 'Asia/Dili', 'Asia/Dubai', 'Asia/Dushanbe', 'Asia/Famagusta', 'Asia/Gaza', 'Asia/Harbin', 'Asia/Hebron', 'Asia/Ho_Chi_Minh', 'Asia/Hong_Kong', 'Asia/Hovd', 'Asia/Irkutsk', 'Asia/Istanbul', 'Asia/Jakarta', 'Asia/Jayapura', 'Asia/Jerusalem', 'Asia/Kabul', 'Asia/Kamchatka', 'Asia/Karachi', 'Asia/Kashgar', 'Asia/Kathmandu', 'Asia/Katmandu', 'Asia/Khandyga', 'Asia/Kolkata', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Kuwait', 'Asia/Macao', 'Asia/Macau', 'Asia/Magadan', 'Asia/Makassar', 'Asia/Manila', 'Asia/Muscat', 'Asia/Nicosia', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Oral', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Pyongyang', 'Asia/Qatar', 'Asia/Qostanay', 'Asia/Qyzylorda', 'Asia/Rangoon', 'Asia/Riyadh', 'Asia/Saigon', 'Asia/Sakhalin', 'Asia/Samarkand', 'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Srednekolymsk', 'Asia/Taipei', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Tehran', 'Asia/Tel_Aviv', 'Asia/Thimbu', 'Asia/Thimphu', 'Asia/Tokyo', 'Asia/Tomsk', 'Asia/Ujung_Pandang', 'Asia/Ulaanbaatar', 'Asia/Ulan_Bator', 'Asia/Urumqi', 'Asia/Ust-Nera', 'Asia/Vientiane', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yangon', 'Asia/Yekaterinburg', 'Asia/Yerevan', 'Atlantic/Azores', 'Atlantic/Bermuda', 'Atlantic/Canary', 'Atlantic/Cape_Verde', 'Atlantic/Faeroe', 'Atlantic/Faroe', 'Atlantic/Jan_Mayen', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/South_Georgia', 'Atlantic/St_Helena', 'Atlantic/Stanley', 'Australia/ACT', 'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Broken_Hill', 'Australia/Canberra', 'Australia/Currie', 'Australia/Darwin', 'Australia/Eucla', 'Australia/Hobart', 'Australia/LHI', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/NSW', 'Australia/North', 'Australia/Perth', 'Australia/Queensland', 'Australia/South', 'Australia/Sydney', 'Australia/Tasmania', 'Australia/Victoria', 'Australia/West', 'Australia/Yancowinna', 'Brazil/Acre', 'Brazil/DeNoronha', 'Brazil/East', 'Brazil/West', 'CET', 'CST6CDT', 'Canada/Atlantic', 'Canada/Central', 'Canada/Eastern', 'Canada/Mountain', 'Canada/Newfoundland', 'Canada/Pacific', 'Canada/Saskatchewan', 'Canada/Yukon', 'Chile/Continental', 'Chile/EasterIsland', 'Cuba', 'EET', 'EST', 'EST5EDT', 'Egypt', 'Eire', 'Etc/GMT', 'Etc/GMT+0', 'Etc/GMT+1', 'Etc/GMT+10', 'Etc/GMT+11', 'Etc/GMT+12', 'Etc/GMT+2', 'Etc/GMT+3', 'Etc/GMT+4', 'Etc/GMT+5', 'Etc/GMT+6', 'Etc/GMT+7', 'Etc/GMT+8', 'Etc/GMT+9', 'Etc/GMT-0', 'Etc/GMT-1', 'Etc/GMT-10', 'Etc/GMT-11', 'Etc/GMT-12', 'Etc/GMT-13', 'Etc/GMT-14', 'Etc/GMT-2', 'Etc/GMT-3', 'Etc/GMT-4', 'Etc/GMT-5', 'Etc/GMT-6', 'Etc/GMT-7', 'Etc/GMT-8', 'Etc/GMT-9', 'Etc/GMT0', 'Etc/Greenwich', 'Etc/UCT', 'Etc/UTC', 'Etc/Universal', 'Etc/Zulu', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Astrakhan', 'Europe/Athens', 'Europe/Belfast', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Busingen', 'Europe/Chisinau', 'Europe/Copenhagen', 'Europe/Dublin', 'Europe/Gibraltar', 'Europe/Guernsey', 'Europe/Helsinki', 'Europe/Isle_of_Man', 'Europe/Istanbul', 'Europe/Jersey', 'Europe/Kaliningrad', 'Europe/Kiev', 'Europe/Kirov', 'Europe/Lisbon', 'Europe/Ljubljana', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Mariehamn', 'Europe/Minsk', 'Europe/Monaco', 'Europe/Moscow', 'Europe/Nicosia', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Riga', 'Europe/Rome', 'Europe/Samara', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Saratov', 'Europe/Simferopol', 'Europe/Skopje', 'Europe/Sofia', 'Europe/Stockholm', 'Europe/Tallinn', 'Europe/Tirane', 'Europe/Tiraspol', 'Europe/Ulyanovsk', 'Europe/Uzhgorod', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Vilnius', 'Europe/Volgograd', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zaporozhye', 'Europe/Zurich', 'GB', 'GB-Eire', 'GMT', 'GMT+0', 'GMT-0', 'GMT0', 'Greenwich', 'HST', 'Hongkong', 'Iceland', 'Indian/Antananarivo', 'Indian/Chagos', 'Indian/Christmas', 'Indian/Cocos', 'Indian/Comoro', 'Indian/Kerguelen', 'Indian/Mahe', 'Indian/Maldives', 'Indian/Mauritius', 'Indian/Mayotte', 'Indian/Reunion', 'Iran', 'Israel', 'Jamaica', 'Japan', 'Kwajalein', 'Libya', 'MET', 'MST', 'MST7MDT', 'Mexico/BajaNorte', 'Mexico/BajaSur', 'Mexico/General', 'NZ', 'NZ-CHAT', 'Navajo', 'PRC', 'PST8PDT', 'Pacific/Apia', 'Pacific/Auckland', 'Pacific/Bougainville', 'Pacific/Chatham', 'Pacific/Chuuk', 'Pacific/Easter', 'Pacific/Efate', 'Pacific/Enderbury', 'Pacific/Fakaofo', 'Pacific/Fiji', 'Pacific/Funafuti', 'Pacific/Galapagos', 'Pacific/Gambier', 'Pacific/Guadalcanal', 'Pacific/Guam', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Kanton', 'Pacific/Kiritimati', 'Pacific/Kosrae', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Marquesas', 'Pacific/Midway', 'Pacific/Nauru', 'Pacific/Niue', 'Pacific/Norfolk', 'Pacific/Noumea', 'Pacific/Pago_Pago', 'Pacific/Palau', 'Pacific/Pitcairn', 'Pacific/Pohnpei', 'Pacific/Ponape', 'Pacific/Port_Moresby', 'Pacific/Rarotonga', 'Pacific/Saipan', 'Pacific/Samoa', 'Pacific/Tahiti', 'Pacific/Tarawa', 'Pacific/Tongatapu', 'Pacific/Truk', 'Pacific/Wake', 'Pacific/Wallis', 'Pacific/Yap', 'Poland', 'Portugal', 'ROC', 'ROK', 'Singapore', 'Turkey', 'UCT', 'US/Alaska', 'US/Aleutian', 'US/Arizona', 'US/Central', 'US/East-Indiana', 'US/Eastern', 'US/Hawaii', 'US/Indiana-Starke', 'US/Michigan', 'US/Mountain', 'US/Pacific', 'US/Samoa', 'UTC', 'Universal', 'W-SU', 'WET', 'Zulu']

In [23]:
ercot.loc['2017-03-12']

                      ercot_load     dow  is_weekday  is_obs_holiday
datetime
2017-03-12 00:00:00  9120.385718  Sunday           0               0
2017-03-12 01:00:00  8579.644600  Sunday           0               0
2017-03-12 02:00:00  8251.748166  Sunday           0               0
2017-03-12 04:00:00  8016.291377  Sunday           0               0
2017-03-12 05:00:00  7894.080492  Sunday           0               0
2017-03-12 06:00:00  7871.827685  Sunday           0               0
2017-03-12 07:00:00  8034.402546  Sunday           0               0
2017-03-12 08:00:00  8192.101434  Sunday           0               0
2017-03-12 09:00:00  8395.224430  Sunday           0               0
2017-03-12 10:00:00  8817.761577  Sunday           0               0
2017-03-12 11:00:00  9218.897392  Sunday           0               0
2017-03-12 12:00:00  9535.095465  Sunday           0               0
2017-03-12 13:00:00  9651.844482  Sunday           0               0
2017-03-12 14:00:00  9603.323580  Sunday           0               0
2017-03-12 15:00:00  9460.848568  Sunday           0               0
2017-03-12 16:00:00  9295.347442  Sunday           0               0
2017-03-12 17:00:00  9204.943138  Sunday           0               0
2017-03-12 18:00:00  9194.145087  Sunday           0               0
2017-03-12 19:00:00  9231.290243  Sunday           0               0
2017-03-12 20:00:00  9635.354626  Sunday           0               0
2017-03-12 21:00:00  9880.170733  Sunday           0               0
2017-03-12 22:00:00  9707.682717  Sunday           0               0
2017-03-12 23:00:00  9371.168940  Sunday           0               0

In [19]:
ercot.loc['2017-11-05']

                       ercot_load     dow  is_weekday  is_obs_holiday
datetime
2017-11-05 00:00:00  11692.944342  Sunday           0               0
2017-11-05 01:00:00  11086.848799  Sunday           0               0
2017-11-05 02:00:00  10677.703425  Sunday           0               0
2017-11-05 02:00:00  10377.230056  Sunday           0               0
2017-11-05 03:00:00  10256.523453  Sunday           0               0
2017-11-05 04:00:00  10172.758178  Sunday           0               0
2017-11-05 05:00:00  10120.696313  Sunday           0               0
2017-11-05 06:00:00  10169.707241  Sunday           0               0
2017-11-05 07:00:00  10240.548497  Sunday           0               0
2017-11-05 08:00:00  10541.387753  Sunday           0               0
2017-11-05 09:00:00  11438.051520  Sunday           0               0
2017-11-05 10:00:00  12215.178795  Sunday           0               0
2017-11-05 11:00:00  12990.132889  Sunday           0               0
2017-11-05 12:00:00  13729.734459  Sunday           0               0
2017-11-05 13:00:00  14417.922675  Sunday           0               0
2017-11-05 14:00:00  14893.525286  Sunday           0               0
2017-11-05 15:00:00  15157.496619  Sunday           0               0
2017-11-05 16:00:00  15185.961106  Sunday           0               0
2017-11-05 17:00:00  14787.620836  Sunday           0               0
2017-11-05 18:00:00  14423.909032  Sunday           0               0
2017-11-05 19:00:00  14283.559118  Sunday           0               0
2017-11-05 20:00:00  13805.181302  Sunday           0               0
2017-11-05 21:00:00  13302.887699  Sunday           0               0
2017-11-05 22:00:00  12762.023408  Sunday           0               0
2017-11-05 23:00:00  12054.982904  Sunday           0               0

In [17]:
ercot.loc['2010-03-14']

                      ercot_load     dow  is_weekday  is_obs_holiday
datetime
2010-03-14 00:00:00  7521.589500  Sunday           0               0
2010-03-14 01:00:00  7032.989051  Sunday           0               0
2010-03-14 03:00:00  6849.691844  Sunday           0               0
2010-03-14 04:00:00  6719.875617  Sunday           0               0
2010-03-14 05:00:00  6732.124334  Sunday           0               0
2010-03-14 06:00:00  6837.968300  Sunday           0               0
2010-03-14 07:00:00  7019.089435  Sunday           0               0
2010-03-14 08:00:00  7162.896788  Sunday           0               0
2010-03-14 09:00:00  7184.913734  Sunday           0               0
2010-03-14 10:00:00  7391.466893  Sunday           0               0
2010-03-14 11:00:00  7617.179717  Sunday           0               0
2010-03-14 12:00:00  7801.790891  Sunday           0               0
2010-03-14 13:00:00  8058.543535  Sunday           0               0
2010-03-14 14:00:00  8209.974122  Sunday           0               0
2010-03-14 15:00:00  8433.703449  Sunday           0               0
2010-03-14 16:00:00  8586.144636  Sunday           0               0
2010-03-14 17:00:00  8736.262413  Sunday           0               0
2010-03-14 18:00:00  8875.448729  Sunday           0               0
2010-03-14 19:00:00  8806.769260  Sunday           0               0
2010-03-14 20:00:00  9009.113671  Sunday           0               0
2010-03-14 21:00:00  9212.130622  Sunday           0               0
2010-03-14 22:00:00  8860.994757  Sunday           0               0
2010-03-14 23:00:00  8404.543730  Sunday           0               0

In [16]:
weather.loc['2010-03-14']

,hs_temp,hs_feelslike,hs_dew,hs_humidity,hs_precip,hs_windgust,hs_windspeed,hs_winddir,hs_sealevelpressure,hs_cloudcover,...,vc_precip,vc_windgust,vc_windspeed,vc_winddir,vc_sealevelpressure,vc_cloudcover,vc_visibility,vc_solarradiation,vc_solarenergy,vc_uvindex
datetime,,,,,,,,,,,,,,,,,,,,,
2010-03-14 00:00:00,61.5,61.5,39.3,43.76,0.0,NaN,3.6,200.0,1011.2,4.4,...,0.0,NaN,3.5,170.0,1010.4,0.0,9.9,0.0,NaN,0.0
2010-03-14 01:00:00,61.3,61.3,38.0,42.12,0.0,NaN,4.0,222.0,1011.0,0.0,...,0.0,NaN,6.9,180.0,1009.9,0.0,9.9,0.0,NaN,0.0
2010-03-14 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03-14 03:00:00,61.0,61.0,41.4,48.41,0.0,NaN,4.9,231.0,1010.9,0.0,...,0.0,NaN,4.8,170.0,1009.7,0.0,9.9,0.0,NaN,0.0
2010-03-14 04:00:00,61.0,61.0,39.8,45.65,0.0,NaN,7.7,222.0,1010.3,0.0,...,0.0,NaN,0.3,13.0,1009.5,0.0,9.9,0.0,NaN,0.0
2010-03-14 05:00:00,58.9,58.9,41.4,52.14,0.0,NaN,5.8,222.0,1010.4,0.0,...,0.0,NaN,3.4,123.0,1009.8,0.0,8.8,0.0,NaN,0.0
2010-03-14 06:00:00,57.4,57.4,45.9,65.50,0.0,NaN,6.8,222.0,1010.7,4.4,...,0.0,NaN,4.7,170.0,1010.1,0.0,9.9,0.0,NaN,0.0
2010-03-14 07:00:00,57.4,57.4,47.4,69.36,0.0,NaN,4.9,231.0,1011.4,4.4,...,0.0,NaN,5.8,171.0,1010.7,0.0,6.1,5.0,0.0,0.0
2010-03-14 08:00:00,55.9,55.9,47.4,73.26,0.0,NaN,0.0,0.0,1012.4,14.1,...,0.0,NaN,3.4,151.0,1011.1,50.3,0.1,66.3,0.2,1.0
2010-03-14 09:00:00,61.5,61.5,49.5,64.62,0.0,NaN,0.0,0.0,1013.1,14.1,...,0.0,NaN,4.7,160.0,1011.8,49.4,0.1,154.1,0.6,2.0
2010-03-14 10:00:00,65.7,65.7,56.4,71.97,0.0,NaN,4.9,231.0,1013.9,7.9,...,0.0,NaN,12.7,190.0,1012.4,0.2,9.9,250.1,0.9,3.0
2010-03-14 11:00:00,70.8,70.8,55.8,58.94,0.0,NaN,5.2,314.0,1014.5,14.1,...,0.0,NaN,17.1,200.0,1012.8,0.0,9.9,366.0,1.3,4.0
2010-03-14 12:00:00,72.9,72.9,52.4,48.66,0.0,NaN,5.4,193.0,1014.4,14.1,...,0.0,NaN,14.1,190.0,1012.6,0.0,9.9,523.5,1.9,5.0
2010-03-14 13:00:00,75.0,75.0,53.7,47.47,0.0,NaN,0.7,208.3,1013.9,14.1,...,0.0,NaN,11.5,200.0,1012.4,0.0,9.9,739.5,2.7,7.0
2010-03-14 14:00:00,76.8,76.8,53.7,44.71,0.0,NaN,4.9,246.0,1013.1,14.1,...,0.0,NaN,16.1,190.0,1011.8,0.0,9.9,638.8,2.3,6.0
2010-03-14 15:00:00,80.4,79.7,49.8,34.42,0.0,NaN,5.1,176.0,1012.3,14.1,...,0.0,23.0,16.1,200.0,1011.2,0.0,9.9,445.1,1.6,4.0
2010-03-14 16:00:00,80.1,79.4,48.2,32.71,0.0,NaN,5.4,186.0,1012.2,14.1,...,0.0,23.0,15.0,190.0,1011.2,0.0,9.9,314.9,1.1,3.0
2010-03-14 17:00:00,76.8,76.8,54.5,46.13,0.0,NaN,11.4,127.0,1012.0,14.1,...,0.0,NaN,10.4,190.0,1011.0,0.0,9.9,205.4,0.7,2.0
2010-03-14 18:00:00,73.5,73.5,62.4,68.29,0.0,NaN,13.1,127.0,1011.7,14.1,...,0.0,NaN,11.5,190.0,1011.1,0.0,9.9,136.8,0.5,1.0
2010-03-14 19:00:00,70.2,70.2,62.4,76.40,0.0,NaN,11.1,138.0,1012.1,14.1,...,0.0,NaN,10.3,161.0,1011.6,0.0,9.9,9.0,0.0,0.0
2010-03-14 20:00:00,66.3,66.3,62.4,87.31,0.0,NaN,10.1,158.0,1013.0,14.1,...,0.0,NaN,10.2,179.0,1012.2,0.0,9.9,0.0,NaN,0.0
2010-03-14 21:00:00,64.5,64.5,62.4,92.95,0.0,NaN,9.6,162.0,1013.7,14.1,...,0.0,NaN,6.9,140.0,1012.8,0.0,9.9,0.0,NaN,0.0
2010-03-14 22:00:00,62.7,62.7,62.4,99.00,0.0,NaN,6.9,172.0,1014.2,39.3,...,0.0,NaN,9.0,139.0,1012.9,0.2,9.9,0.0,NaN,0.0
2010-03-14 23:00:00,62.4,62.4,60.9,94.78,0.0,NaN,5.7,172.0,1014.7,89.9,...,0.0,NaN,5.0,101.0,1013.6,3.0,9.8,0.0,NaN,0.0

In [5]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 109536 entries, 2010-01-01 00:00:00 to 2022-06-30 23:00:00
Data columns (total 56 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   hs_temp              109523 non-null  float64
 1   hs_feelslike         109523 non-null  float64
 2   hs_dew               109523 non-null  float64
 3   hs_humidity          109523 non-null  float64
 4   hs_precip            109523 non-null  float64
 5   hs_windgust          28671 non-null   float64
 6   hs_windspeed         109523 non-null  float64
 7   hs_winddir           109523 non-null  float64
 8   hs_sealevelpressure  109423 non-null  float64
 9   hs_cloudcover        109523 non-null  float64
 10  hs_visibility        109523 non-null  float64
 11  hs_solarradiation    109523 non-null  float64
 12  hs_solarenergy       69235 non-null   float64
 13  hs_uvindex           109523 non-null  float64
 14  gv_temp              109523 non-null  float64
 15  gv_feelslike         109523 non-null  float64
 16  gv_dew               109523 non-null  float64
 17  gv_humidity          109523 non-null  float64
 18  gv_precip            109523 non-null  float64
 19  gv_windgust          53394 non-null   float64
 20  gv_windspeed         109523 non-null  float64
 21  gv_winddir           109523 non-null  float64
 22  gv_sealevelpressure  109520 non-null  float64
 23  gv_cloudcover        109523 non-null  float64
 24  gv_visibility        109521 non-null  float64
 25  gv_solarradiation    99610 non-null   float64
 26  gv_solarenergy       66873 non-null   float64
 27  gv_uvindex           99610 non-null   float64
 28  pl_temp              109523 non-null  float64
 29  pl_feelslike         109523 non-null  float64
 30  pl_dew               109523 non-null  float64
 31  pl_humidity          109523 non-null  float64
 32  pl_precip            109523 non-null  float64
 33  pl_windgust          49041 non-null   float64
 34  pl_windspeed         109523 non-null  float64
 35  pl_winddir           109523 non-null  float64
 36  pl_sealevelpressure  109348 non-null  float64
 37  pl_cloudcover        109523 non-null  float64
 38  pl_visibility        109515 non-null  float64
 39  pl_solarradiation    109523 non-null  float64
 40  pl_solarenergy       63207 non-null   float64
 41  pl_uvindex           109523 non-null  float64
 42  vc_temp              109523 non-null  float64
 43  vc_feelslike         109523 non-null  float64
 44  vc_dew               109523 non-null  float64
 45  vc_humidity          109523 non-null  float64
 46  vc_precip            109523 non-null  float64
 47  vc_windgust          37683 non-null   float64
 48  vc_windspeed         109523 non-null  float64
 49  vc_winddir           109523 non-null  float64
 50  vc_sealevelpressure  109446 non-null  float64
 51  vc_cloudcover        109523 non-null  float64
 52  vc_visibility        109488 non-null  float64
 53  vc_solarradiation    109523 non-null  float64
 54  vc_solarenergy       64816 non-null   float64
 55  vc_uvindex           109523 non-null  float64
dtypes: float64(56)
memory usage: 47.6 MB